### PR TITLE
remove oneplus2

### PR DESCRIPTION
**Pull request by kunalshah912**

### CODE REVIEW

**Comment by msfjarvis** [comment]
-.-

**Comment by msfjarvis** [comment]
Could have talked to me if OTA wasn't working ONLY for you duh, it's like 5 lines of code for me to fix it for you -_-

**Comment by kunalshah912** [comment]
To be clear ! OTA doesn't work on any cosmic supported device ! and i have asked the team several times about it and they were like this doesn't work and we have to implement XOS or PA one ! If it was that easy and all supported devices have OTA working then i am on the wrong side and i may be a noob to solve it! the team feels i am just complaining about it and spamming them , so i think you guys will find a better one ! thanks for all the support you guys gave ! and BTW i am not a chutiya ! Thank You

**Comment by msfjarvis** [comment]
It doesn't work because @sagarshah1729 has it all fucked up mkay? stop being a bitch because fucking OTA doesn't work

**Comment by msfjarvis** [comment]
SlimOTA will never work for Cosmic btw, just checked it all up.

**Comment by Shreeesha** [comment]
Make it work

**Comment by aditheking** [comment]
Shreesha sir on cos wew

**Comment by msfjarvis** [comment]
>Make it work

Meh

**Pull request closed without merging**
